<<<<<<< HEAD
CREATE TABLE inventory (
  id            SERIAL PRIMARY KEY,
  name          TEXT NOT NULL,
  type          TEXT,
  area          TEXT,
  location      TEXT,
  status        TEXT,
  quantity      INTEGER,
  condition     TEXT,
  "itemImage"   TEXT,
  "checkOutBy"  TEXT,
  "lastUpdated" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  tags          TEXT,
  notes         TEXT
);
=======
-- Supabase inventory table schema.
--
-- How to apply:
--   1. Open your Supabase project → SQL Editor → New Query
--   2. Paste this entire file and click Run
--
-- Column naming: camelCase columns (itemImage, checkOutBy, lastUpdated) are quoted
-- so PostgreSQL preserves their case. The Supabase JS client and the frontend both
-- expect these exact names — do not rename them.

create table public.inventory (
  id            bigint generated by default as identity primary key,
  name          text        not null,
  type          text,
  area          text,
  location      text,
  status        text,
  quantity      integer,
  condition     text,
  "itemImage"   text,
  "checkOutBy"  text,
  "lastUpdated"   timestamptz default now(),
  tags            text,
  notes           text,
  "needsRestock"  integer     default 0
);
>>>>>>> 796ac6e795cc3b6b27826a7901c7c0c2ce809c09
