-- Supabase schema for Spare Pit inventory
create table public.inventory (
  id bigint generated by default as identity primary key,
  name text not null,
  type text,
  area text,
  location text,
  status text,
  quantity integer,
  condition text,
  itemImage text,
  checkOutBy text,
  lastUpdated timestamptz default now(),
  tags text,
  notes text
);