-- Supabase inventory table schema.
--
-- How to apply:
--   1. Open your Supabase project → SQL Editor → New Query
--   2. Paste this entire file and click Run
--
-- Column naming: camelCase columns (itemImage, checkOutBy, lastUpdated) are quoted
-- so PostgreSQL preserves their case. The Supabase JS client and the frontend both
-- expect these exact names — do not rename them.

create table public.inventory (
  id            bigint generated by default as identity primary key,
  name          text        not null,
  type          text,
  area          text,
  location      text,
  status        text,
  quantity      integer,
  condition     text,
  "itemImage"   text,
  "checkOutBy"  text,
  "lastUpdated"   timestamptz default now(),
  tags            text,
  notes           text,
  "needsRestock"  integer     default 0
);
